### ISSUE TITLE
Map Does Not Display in Panel

### ISSUE THREAD

**Issue by luxlogica** [lekkerduidelijk/kirby-geolocation-field#3]
My blueprint looks like this:

```
fields:
  title:
    label: Title
    type:  text
  location:
    label: Location
    type: geolocation
```

...and in the Panel I see this:

![screen shot 2015-08-23 at 12 19 09 pm](https://cloud.githubusercontent.com/assets/2994472/9426616/3822e99a-4991-11e5-870b-a61e81d0a93f.png)

As you can see, I've followed the installation and setup instructions, but the map is still not showing in the Panel. Also, default button and placeholder texts show up in Dutch - is that how it's supposed to be?
